CREATE TABLE `persons` (
`Id` int(10) UNSIGNED NULL DEFAULT NULL,
`FirstName` VARCHAR(50) NULL DEFAULT NULL,
`LastName` VARCHAR(50) NULL DEFAULT NULL,
`Address` VARCHAR(50) NULL DEFAULT NULL,
`Gender` VARCHAR(50) NULL DEFAULT NULL
)
ENGINE=InnoDB
;

ALTER TABLE `restwithaspnetcoreudemy`.`persons` 
CHANGE COLUMN `Id` `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
ADD PRIMARY KEY (`Id`);
;
